# Generated by Django 6.0.3 on 2026-04-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('type', models.CharField(choices=[('work', 'Work'), ('education', 'Education'), ('digital_nomad', 'Digital nomad'), ('tourist', 'Tourist'), ('residency', 'Residency'), ('investment', 'Investment'), ('family', 'Family')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('roadmap', models.TextField(blank=True, help_text='Optional overview/notes. Use Roadmap Steps below for ordered steps.')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g. USD, EUR).', max_length=3)),
                ('stay_duration_days', models.PositiveIntegerField(blank=True, help_text='Typical allowed stay in days (if applicable).', null=True)),
                ('process_time_days', models.PositiveIntegerField(blank=True, help_text='Typical processing time in days (if known).', null=True)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1 (Easy)'), (2, '2 (Medium)'), (3, '3 (Hard)')], default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visas', to='countries.country')),
            ],
            options={
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='visas.visa')),
            ],
            options={
                'ordering': ['visa', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='visas.visa')),
            ],
            options={
                'verbose_name': 'visa FAQ',
                'verbose_name_plural': 'visa FAQs',
                'ordering': ['visa', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisaRoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='visas.visa')),
            ],
            options={
                'verbose_name': 'visa roadmap step',
                'verbose_name_plural': 'visa roadmap steps',
                'ordering': ['visa', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisaTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('content', models.TextField()),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='visas.visa')),
            ],
            options={
                'verbose_name': 'visa tip',
                'verbose_name_plural': 'visa tips',
                'ordering': ['visa', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['country', 'type'], name='visas_visa_country_b704c9_idx'),
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['is_active', 'is_featured'], name='visas_visa_is_acti_6c4edb_idx'),
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['slug'], name='visas_visa_slug_fd0435_idx'),
        ),
        migrations.AddConstraint(
            model_name='visa',
            constraint=models.UniqueConstraint(fields=('country', 'slug'), name='uniq_visa_country_slug'),
        ),
        migrations.AddConstraint(
            model_name='requireddocument',
            constraint=models.UniqueConstraint(fields=('visa', 'order'), name='uniq_visa_required_document_order'),
        ),
        migrations.AddConstraint(
            model_name='visafaq',
            constraint=models.UniqueConstraint(fields=('visa', 'order'), name='uniq_visa_faq_order'),
        ),
        migrations.AddConstraint(
            model_name='visaroadmapstep',
            constraint=models.UniqueConstraint(fields=('visa', 'order'), name='uniq_visa_roadmap_step_order'),
        ),
        migrations.AddConstraint(
            model_name='visatip',
            constraint=models.UniqueConstraint(fields=('visa', 'order'), name='uniq_visa_tip_order'),
        ),
    ]
