# Generated by Django 6.0.3 on 2026-04-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visatip',
            name='content',
        ),
        migrations.AddField(
            model_name='visatip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visatip',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
