# Generated by Django 6.0.3 on 2026-04-07 13:31

import countries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 (e.g. US, CA, DE).', max_length=2, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=countries.models.country_image_upload_to)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='countries_c_code_79f189_idx'), models.Index(fields=['slug'], name='countries_c_slug_89e9aa_idx'), models.Index(fields=['is_active', 'is_popular'], name='countries_c_is_acti_81a1fe_idx')],
            },
        ),
    ]
